### ISSUE TITLE
JQuery support

### ISSUE THREAD

**Issue by NathanBnm** [apache/cordova-eslint#15]
I'm using JQuery too, is there a way to combine both in order to accept JQuery syntax?
I tried to add `extends: 'jquery'` too but it's overwriting cordova eslint rules.

**Comment by raphinesse** [comment]
Firstly, let me clarify something. The Readme states:
> This repository centralizes the ESLint configuration used for Cordova's development.

What this means is that this package is primarily intended for linting the JavaScript sources of  Cordova's _internal packages_ (i.e. of GitHub repositories that start with `apache/cordova-`). We probably need to make this clearer in the Readme. Or put another way: this package is not intended to be used for linting Cordova apps.

You can certainly use this package to lint your app. If it works for you, then that's fine. But if not, we unfortunately cannot provide support for making it work. Neither do we want to add complexity to make this package more widely applicable. It is intended for internal use and should stay as simple as possible.

Regarding your specific issue: You might have to change the order in which you extend from the configs. ESLint is pretty smart when merging configs, but there still might be conflicting rules that you have to resolve yourself. `eslint --print-config <file>` can help you to figure out what the effective config looks like for a given file.

**Comment by NathanBnm** [comment]
Thanks for your explanation :)

> We probably need to make this clearer in the Readme. Or put another way: this package is not intended to be used for linting Cordova apps.

It's a bit confusing so I assume it would be better if you add it to the README.

> 
> Regarding your specific issue: You might have to change the order in which you extend from the configs. ESLint is pretty smart when merging configs, but there still might be conflicting rules that you have to resolve yourself. `eslint --print-config <file>` can help you to figure out what the effective config looks like for a given file.

Thanks for your help, I'll take a look.
